package nsbm_higher_education;

import nsbm_higher_education.student.StudentDashbord;

public class DashBoard extends javax.swing.JFrame {
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labjButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        instructorButton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        subjectjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setPreferredSize(new java.awt.Dimension(1350, 730));
        getContentPane().setLayout(null);

        labjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/labb.jpg"))); // NOI18N
        labjButton.setText("jButton2");
        labjButton.setToolTipText("");
        labjButton.setAlignmentY(0.0F);
        getContentPane().add(labjButton);
        labjButton.setBounds(1000, 310, 190, 200);

        studentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NEW STU.jpg"))); // NOI18N
        studentButton.setText("jButton2");
        studentButton.setToolTipText("");
        studentButton.setAlignmentY(0.0F);
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton);
        studentButton.setBounds(120, 310, 190, 200);

        instructorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NEW.jpg"))); // NOI18N
        instructorButton.setText("jButton2");
        instructorButton.setToolTipText("");
        instructorButton.setAlignmentY(0.0F);
        getContentPane().add(instructorButton);
        instructorButton.setBounds(350, 310, 190, 200);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LEC.jpg"))); // NOI18N
        jButton10.setText("jButton2");
        jButton10.setToolTipText("");
        jButton10.setAlignmentY(0.0F);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(560, 310, 190, 200);

        subjectjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SUBJE.jpg"))); // NOI18N
        subjectjButton.setToolTipText("");
        subjectjButton.setAlignmentY(0.0F);
        getContentPane().add(subjectjButton);
        subjectjButton.setBounds(780, 310, 190, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setPreferredSize(new java.awt.Dimension(1350, 730));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1410, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        StudentDashbord studentDashboard = new StudentDashbord();
        studentDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton instructorButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton labjButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton subjectjButton;
    // End of variables declaration//GEN-END:variables
}
